version 2:

sources:
  - name: raw
    schema: gz_raw_data
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        freshness:
          warn_after:
            count: 90
            period: day
        loaded_at_field: "CAST( date_date as TIMESTAMP)"
        description: sales of greenweez/ we have one row per products_id found in each orders_id
        columns:
          - name: date_date
            description: date of pruchase
          - name: orders_id
            description: id of the purchase made
          - name: products_id
            description: the id of each product that is present in a purchase
          - name: revenue
            description: revenue made per product_id per order_id
          - name: quantity
            description: quantity of the product sold within that order
      - name: product
        identifier: raw_product
        description: list of products sold at greenweez
        columns:
          - name: products_id
            description: unique identifier for each product
          - name: pruschase price
            description: price of each product
      - name: ship
        identifier: raw_gz_ship
        description: shipping information for orders at greenweez
        columns:
          - name: orders_id
            description: primary key of table
          - name: shipping_fee
            description: shipping fee applied to order
          - name: log_cost
            description: logistics cost of order
          - name: ship_cost
            description: shipping cost of order
      - name: int_sales_margin
        description: cleaned sales table
        columns:
          - name: products_id
            description: one of the columns for the primary key 
          - name: date_date
            description: date of the order
          - name: orders_id
            description: one of the columns for the primary key 
          - name: revenue
            description: revenue of each order
          - name: quantity
            description: number of products per order
          - name: purchase_price
            description: price of each product sold
          - name: purchase_cost
            description: Quantity * Purchase_price
          - name: margin
            description: Revenue - Purchase_cost
      - name: int_orders_operational
        description: grouped table
        columns:
          - name: orders_id
            description: primary key of the table 
          - name: date_date
            description: date of the orders
          - name: revenue
            description: sum of revenue of each order
          - name: quantity
            description: number of products in each order
          - name: purchase_cost
            description: Quantity * Purchase_price
          - name: margin
            description: Revenue - Purchase_cost
          - name: operational_margin
            description: margin + shipping fee - log_cost - ship_cost
      - name: int_orders_margin
        description: cleaned table
        columns:
          - name: orders_id
            description: table primary key 
          - name: date_date
            description: date of the orders
          - name: revenue
            description: sum of revenue of each order
          - name: quantity
            description: number of products in each order
          - name: purchase_cost
            description: Quantity * Purchase_price
          - name: margin
            description: Revenue - Purchase_cost
      - name: finance_days
        description: mart model for the finance team 
        columns:
        - name: date_date
          description: unique identifier
        - name: nb_transactions
          description: cout of number of transactions on that specific day 
        - name: revenue
          description: total revenue 
        - name: average_basket
          description: average revenue per each order 
        - name: margin
          description:  Revenue - Purchase_cost
        - name: operational_margin
          description: margin + shipping fee - log_cost - ship_cost
      - name: adwords
        identifier: raw_gz_adwords
        columns:
        - name: date_date
        - name: paid_source
        - name: campaign_key
        - name: campaign_name
        - name: ads_cost
        - name: impression 
        - name: click
      - name: bing
        identifier: raw_gz_bing
        columns:
        - name: date_date
        - name: paid_source
        - name: campaign_key
        - name: campaign_name
        - name: ads_cost
        - name: impression 
        - name: click
      - name: criteo
        identifier: raw_gz_criteo
        columns:
        - name: date_date
        - name: paid_source
        - name: campaign_key
        - name: campaign_name
        - name: ads_cost
        - name: impression 
        - name: click
      - name: facebook 
        identifier: raw_gz_facebook
        columns:
        - name: date_date
        - name: paid_source
        - name: campaign_key
        - name: campaign_name
        - name: ads_cost
        - name: impression 
        - name: click
      - name: int_campaigns 
        columns:
        - name: date_date
        - name: paid_source
        - name: campaign_key
        - name: campaign_name
        - name: ads_cost
        - name: impression 
        - name: click
      - name: int_campaigns_day
        columns:
        - name: date_date
        - name: ads_cost 
        - name: ads_impression
        - name: ads_clicks
      - name: finance_campaigns_day
        columns:
          - name: date_date
          - name: nb_transactions
          - name: revenue
          - name: average_basket
          - name: margin
          - name: operational_margin
          - name: ads_cost
          - name: ads_impression
          - name: ads_click
          - name: ads_margin